name: Python Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build with PyInstaller
      run: pyinstaller --onefile soja.py

    - name: Copy accompanying files
      run: |
        copy config.ini.example dist\config.ini
        curl -L -o dist/SDL2-2.28.5-win32-x64.zip https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-2.28.5-win32-x64.zip
        powershell -Command "Expand-Archive -Path dist/SDL2-2.28.5-win32-x64.zip -DestinationPath dist"
        copy dist/SDL2-2.28.5/x64/SDL2.dll dist/SDL2.dll
        del dist/SDL2-2.28.5-win32-x64.zip
        rmdir /s /q dist/SDL2-2.28.5
    - name: Create zip file
      run: |
        cd dist
        powershell Compress-Archive -Path * -DestinationPath .\soja.zip

    - name: Update release tag to latest commit
      run: |
        git tag -f release-${{ github.ref_name }}
        git push origin -f release-${{ github.ref_name }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/soja.zip
        tag: release-${{ github.ref_name }}
        overwrite: true